version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.225.159
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  
  registry-service:
      image: Banking/registry-service
      container_name: registry-service
      restart: always 
      ports:
        - 8761:8761
  
  gateway-service:
      image: Banking/gateway-service
      container_name: gateway-service
      restart: always 
      ports:
        - 8111:8111 
      depends_on:
      - registry-service
      environment:
        REGISTRY_SERVER_HOST: registry-service
  
  fundtransfer-service:
      image: Banking/fundtransfer-service
      container_name: fundtransfer-service
      restart: always 
      ports:
        - 8092:8092 
      depends_on:
      - gateway-service
      environment:
        REGISTRY_SERVER_HOST: registry-service
        KAFKA_BOOTSTRAP_SERVERS:  kafka:9092    
  
  transaction-service:
      image: Banking/transaction-service
      container_name: transaction-service
      restart: always 
      ports:
        - 8093:8093  
      depends_on:
      - gateway-service
      environment:
        REGISTRY_SERVER_HOST: registry-service
        KAFKA_BOOTSTRAP_SERVERS:  kafka:9092  

  account-service:
      image: Banking/account-service
      container_name: account-service
      restart: always 
      ports:
        - 8091:8091 
      depends_on:
      - gateway-service
      environment:
      	REGISTRY_SERVER_HOST: registry-service
	KAFKA_BOOTSTRAP_SERVERS:kafka:9092